<?php

use Illuminate\Support\Str;

return [

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => 'real',

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [
        "sipd_14"=>[
                'driver' => 'pgsql',
                'url' => env('DATABASE_URL'),
                'host' => "103.100.27.222",
                'port' => 5410,
                'database' => 'sipd_14',
                'username' => 'postgres',
                'password' => 'TempeGembus',
                'charset' => 'utf8',
                'prefix' => '',
                'prefix_indexes' => true,
                'schema' => ['anggaran','public','standar_harga','usulan'],
                'sslmode' => 'prefer',
            ],
        "sipd_15"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_15',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_16"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_16',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_18"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_18',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_19"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_19',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_20"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_20',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_21"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_21',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_22"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_22',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_23"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_23',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_24"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_24',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_25"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_25',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_26"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_26',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_27"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_27',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_28"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_28',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_29"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_29',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_71"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_71',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_72"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_72',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_73"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_73',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_74"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_74',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_75"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_75',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_76"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_76',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_77"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_77',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_78"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_78',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_79"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_79',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_80"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_80',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_81"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_81',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_82"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_82',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_83"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_83',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_84"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_84',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_85"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_85',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_86"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_86',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_87"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_87',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_88"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_88',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_89"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_89',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
                    ],
        "sipd_90"=>[
                        'driver' => 'pgsql',
                        'url' => env('DATABASE_URL'),
                        'host' => "103.100.27.222",
                        'port' => 5410,
                        'database' => 'sipd_90',
                        'username' => 'postgres',
                        'password' => 'TempeGembus',
                        'charset' => 'utf8',
                        'prefix' => '',
                        'prefix_indexes' => true,
                        'schema' => ['anggaran','public','standar_harga','usulan'],
                        'sslmode' => 'prefer',
            ],

        'sqlite' => [
            'driver' => 'sqlite',
            'url' => env('DATABASE_URL'),
            'database' => env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),
        ],

        'mysql' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

         'real' => [
            'driver' => 'mysql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => 'dash_pemdes_real',
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => false,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ],

        'pgsql' => [
            'driver' => 'pgsql',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

        'sqlsrv' => [
            'driver' => 'sqlsrv',
            'url' => env('DATABASE_URL'),
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '1433'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk haven't actually been run in the database.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer body of commands than a typical key-value system
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'client' => env('REDIS_CLIENT', 'predis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'predis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],

        'cache' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_CACHE_DB', 1),
        ],

    ],

];
